### ISSUE TITLE
rimraf & npm-run-all

### ISSUE THREAD

**Issue by carlos-cubas** [swimlane/node-microservice-demo#2]
these dependencies aren't included in the package.json  took me a bit to figure it out.

**Comment by amcdnl** [comment]
Ah, didn't realize they were not there. Can you PR them in?>

**Comment by moetelo** [comment]
@amcdnl #3 
closed?

**Comment by marjan-georgiev** [comment]
@Shifu462 yes, that PR has been merged and closed over 3 years ago.

**Comment by moetelo** [comment]
@marjan-georgiev 
I mean that this issue probably must be closed, because it's already fixed.

**Comment by marjan-georgiev** [comment]
Ah, yes, it can be closed.
