### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ischyrus** [swimlane/node-microservice-demo#4]
I'm on a mac. I have node 6.10.0. Here is the error message

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.9.12-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "nodemon" "node-inspector" "npm-run-all" "rimraf"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
`

**Comment by ischyrus** [comment]
I managed to get it up and running. It appears that using node:latest doesn't work, but pointing it to 6.10.0 fixed it.

However, after that. Response validation fails, which I disabled. Then the actual implementation of pets/save doesn't work and it can't even route to /pets

**Comment by abjagtap** [comment]
change `npm i -g nodemon node-inspector` to `npm i -g nodemon node-inspector@0.7.5` in petstore/
https://github.com/node-inspector/node-inspector/issues/1031#issuecomment-450091998
